-- hxds_dr.tb_driverModel definition

CREATE TABLE `tb_driver` (
                             `id` bigint NOT NULL COMMENT '主键',
                             `open_id` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '小程序长期授权',
                             `nickname` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '昵称',
                             `name` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '姓名',
                             `sex` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '性别',
                             `photo` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '头像',
                             `pid` varchar(18) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '身份证号码',
                             `birthday` date DEFAULT NULL COMMENT '生日',
                             `tel` char(11) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '电话',
                             `email` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '邮箱',
                             `mail_address` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '收信地址',
                             `contact_name` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '应急联系人',
                             `contact_tel` char(11) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '应急联系人电话',
                             `real_auth` tinyint DEFAULT NULL COMMENT '1未认证，2已认证，3审核中',
                             `idcard_address` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '身份证地址',
                             `idcard_expiration` date DEFAULT NULL COMMENT '身份证有效期',
                             `idcard_front` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '身份证正面',
                             `idcard_back` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '身份证背面',
                             `idcard_holding` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '手持身份证',
                             `drcard_type` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '驾驶证类型',
                             `drcard_expiration` date DEFAULT NULL COMMENT '驾驶证有效期',
                             `drcard_issue_date` date DEFAULT NULL COMMENT '驾驶证初次领证日期',
                             `drcard_front` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '驾驶证正面',
                             `drcard_back` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '驾驶证背面',
                             `drcard_holding` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '手持驾驶证',
                             `home` json DEFAULT NULL COMMENT '家庭地址，包含地址和定位，用于回家导航',
                             `summary` json DEFAULT NULL COMMENT '摘要信息，level等级，totalOrder接单数，weekOrder周接单，weekComment周好评，appeal正在申诉量',
                             `archive` tinyint(1) NOT NULL COMMENT '是否在腾讯云归档存放司机面部信息',
                             `status` tinyint NOT NULL COMMENT '状态，1正常，2禁用，3.降低接单量',
                             `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
                             PRIMARY KEY (`id`) USING BTREE,
                             UNIQUE KEY `unq_open_id` (`open_id`) USING BTREE,
                             UNIQUE KEY `unq_pid` (`pid`) USING BTREE,
                             KEY `idx_real_auth` (`real_auth`) USING BTREE,
                             KEY `idx_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC COMMENT='代驾司机表';